@extends('layouts.admin')

@section('title', 'Reports')

@section('content')
<div class="flex flex-col gap-6">
    <div>
        <h2 class="font-display text-xl font-bold text-stone-900 dark:text-cream-50">Reports</h2>
        <p class="mt-1 text-sm text-stone-500 dark:text-stone-400">Generate platform reports and download them as spreadsheets.</p>
    </div>

    <div class="card p-5">
        <h3 class="font-display text-lg font-bold text-stone-900 dark:text-cream-50">Generate a report</h3>
        <form method="POST" action="{{ route('admin.reports.generate') }}" class="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4 lg:items-end">
            @csrf
            <div>
                <label for="type" class="input-label">Report type</label>
                <select id="type" name="type" class="input" required>
                    @foreach ($types as $key => $label)
                        <option value="{{ $key }}" @selected(old('type') === $key)>{{ $label }}</option>
                    @endforeach
                </select>
            </div>
            <div>
                <label for="date_from" class="input-label">From</label>
                <input type="date" id="date_from" name="date_from" value="{{ old('date_from') }}" class="input">
            </div>
            <div>
                <label for="date_to" class="input-label">To</label>
                <input type="date" id="date_to" name="date_to" value="{{ old('date_to') }}" class="input">
            </div>
            <button type="submit" class="btn btn-primary">Generate Report</button>
        </form>
    </div>

    <div class="card overflow-hidden">
        <div class="border-b border-stone-100 px-5 py-4 dark:border-leaf-800/60">
            <h3 class="font-display text-lg font-bold text-stone-900 dark:text-cream-50">Generated reports</h3>
        </div>
        <div class="overflow-x-auto">
            <table class="min-w-full divide-y divide-stone-100 dark:divide-leaf-800/60">
                <thead class="bg-stone-50 text-xs font-semibold uppercase tracking-wide text-stone-400 dark:bg-leaf-900/40 dark:text-stone-500">
                    <tr>
                        <th class="px-5 py-3 text-left">Report</th>
                        <th class="px-5 py-3 text-left">Period</th>
                        <th class="px-5 py-3 text-left">Rows</th>
                        <th class="px-5 py-3 text-left">Generated by</th>
                        <th class="px-5 py-3 text-left">Created</th>
                        <th class="px-5 py-3 text-right">Download</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-stone-100 dark:divide-leaf-800/60">
                    @forelse ($reports as $report)
                        @php
                            $params = $report->params ?? [];
                            $period = !empty($params['date_from']) && !empty($params['date_to'])
                                ? $params['date_from'] . ' – ' . $params['date_to']
                                : 'All time';
                        @endphp
                        <tr>
                            <td class="px-5 py-4 font-semibold text-stone-900 dark:text-cream-50">
                                {{ $types[$report->report_type] ?? ucfirst($report->report_type) }}
                            </td>
                            <td class="px-5 py-4 text-stone-500 dark:text-stone-400">{{ $period }}</td>
                            <td class="px-5 py-4 text-stone-500 dark:text-stone-400">{{ $params['rows'] ?? 0 }}</td>
                            <td class="px-5 py-4 text-stone-500 dark:text-stone-400">{{ $report->generator?->name ?? '—' }}</td>
                            <td class="px-5 py-4 text-stone-500 dark:text-stone-400">{{ $report->created_at->format('M j, Y g:i A') }}</td>
                            <td class="px-5 py-4">
                                <div class="flex justify-end">
                                    <a href="{{ route('admin.reports.download', $report) }}" class="btn btn-secondary btn-sm">Download</a>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6" class="px-5 py-12 text-center text-stone-400 dark:text-stone-500">No reports generated yet.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        @if ($reports->hasPages())
            <div class="border-t border-stone-100 px-5 py-4 dark:border-leaf-800/60">
                {{ $reports->links() }}
            </div>
        @endif
    </div>
</div>
@endsection
